const defaultEvents = [
  {
    name: "ui/ux design",
    description: `dive into the world of ui/ux design using figma and adobe among other design tools, 
      build real world designs and convert them to real world sites using.`,
    venue: "Computer Lab 3",
    date: "Mondays",
    startTime: "4PM",
    endTime: "5PM",
    deliveryMode: "Physical",
  },
  {
    name: "ui/ux design",
    description: `dive into the world of ui/ux design using figma and adobe among other design tools, 
      build real world designs and convert them to real world sites using.`,
    venue: "Computer Lab 3",
    date: "Tuesdays",
    startTime: "4PM",
    endTime: "5PM",
    deliveryMode: "Physical",
  },
  {
    name: "web development",
    description: `dive into the world of ui/ux design using figma and adobe among other design tools, 
      build real world designs and convert them to real world sites using.`,
    venue: "Computer Lab 3",
    date: "Wednesdays",
    startTime: "4PM",
    endTime: "5PM",
    deliveryMode: "Physical",
  },
  {
    name: "cyber security and penetration testing",
    description: `dive into the world of ui/ux design using figma and adobe among other design tools, 
      build real world designs and convert them to real world sites using.`,
    venue: "Computer Lab 3",
    date: "Thursdays",
    startTime: "4PM",
    endTime: "5PM",
    deliveryMode: "Physical",
  },
  {
    name: "mobile apps development",
    description: `dive into the world of ui/ux design using figma and adobe among other design tools, 
      build real world designs and convert them to real world sites using.`,
    venue: "Computer Lab 3",
    date: "Fridays",
    startTime: "4PM",
    endTime: "5PM",
    deliveryMode: "Physical",
  },
];

export default defaultEvents;
